// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/token_service.proto

package tokenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackedData    []byte                 `protobuf:"bytes,1,opt,name=packed_data,json=packedData,proto3" json:"packed_data,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SilenceRead   int64                  `protobuf:"varint,3,opt,name=silence_read,json=silenceRead,proto3" json:"silence_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_proto_token_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTokenRequest) GetPackedData() []byte {
	if x != nil {
		return x.PackedData
	}
	return nil
}

func (x *CreateTokenRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CreateTokenRequest) GetSilenceRead() int64 {
	if x != nil {
		return x.SilenceRead
	}
	return 0
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_proto_token_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReadTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTokenRequest) Reset() {
	*x = ReadTokenRequest{}
	mi := &file_proto_token_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokenRequest) ProtoMessage() {}

func (x *ReadTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokenRequest.ProtoReflect.Descriptor instead.
func (*ReadTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReadTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackedData    []byte                 `protobuf:"bytes,1,opt,name=packed_data,json=packedData,proto3" json:"packed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTokenResponse) Reset() {
	*x = ReadTokenResponse{}
	mi := &file_proto_token_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokenResponse) ProtoMessage() {}

func (x *ReadTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokenResponse.ProtoReflect.Descriptor instead.
func (*ReadTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadTokenResponse) GetPackedData() []byte {
	if x != nil {
		return x.PackedData
	}
	return nil
}

type UpdateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PackedData    []byte                 `protobuf:"bytes,2,opt,name=packed_data,json=packedData,proto3" json:"packed_data,omitempty"`
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SilenceRead   int64                  `protobuf:"varint,4,opt,name=silence_read,json=silenceRead,proto3" json:"silence_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenRequest) Reset() {
	*x = UpdateTokenRequest{}
	mi := &file_proto_token_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenRequest) ProtoMessage() {}

func (x *UpdateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateTokenRequest) GetPackedData() []byte {
	if x != nil {
		return x.PackedData
	}
	return nil
}

func (x *UpdateTokenRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *UpdateTokenRequest) GetSilenceRead() int64 {
	if x != nil {
		return x.SilenceRead
	}
	return 0
}

type UpdateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenResponse) Reset() {
	*x = UpdateTokenResponse{}
	mi := &file_proto_token_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenResponse) ProtoMessage() {}

func (x *UpdateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenResponse.ProtoReflect.Descriptor instead.
func (*UpdateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTokenResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DeleteTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenRequest) Reset() {
	*x = DeleteTokenRequest{}
	mi := &file_proto_token_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenRequest) ProtoMessage() {}

func (x *DeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenResponse) Reset() {
	*x = DeleteTokenResponse{}
	mi := &file_proto_token_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenResponse) ProtoMessage() {}

func (x *DeleteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTokenResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_proto_token_service_proto protoreflect.FileDescriptor

const file_proto_token_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/token_service.proto\x12\x05token\"j\n" +
	"\x12CreateTokenRequest\x12\x1f\n" +
	"\vpacked_data\x18\x01 \x01(\fR\n" +
	"packedData\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\x12!\n" +
	"\fsilence_read\x18\x03 \x01(\x03R\vsilenceRead\"+\n" +
	"\x13CreateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"(\n" +
	"\x10ReadTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"4\n" +
	"\x11ReadTokenResponse\x12\x1f\n" +
	"\vpacked_data\x18\x01 \x01(\fR\n" +
	"packedData\"\x80\x01\n" +
	"\x12UpdateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vpacked_data\x18\x02 \x01(\fR\n" +
	"packedData\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12!\n" +
	"\fsilence_read\x18\x04 \x01(\x03R\vsilenceRead\"-\n" +
	"\x13UpdateTokenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"*\n" +
	"\x12DeleteTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x13DeleteTokenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2\xa0\x02\n" +
	"\fTokenService\x12D\n" +
	"\vCreateToken\x12\x19.token.CreateTokenRequest\x1a\x1a.token.CreateTokenResponse\x12>\n" +
	"\tReadToken\x12\x17.token.ReadTokenRequest\x1a\x18.token.ReadTokenResponse\x12D\n" +
	"\vUpdateToken\x12\x19.token.UpdateTokenRequest\x1a\x1a.token.UpdateTokenResponse\x12D\n" +
	"\vDeleteToken\x12\x19.token.DeleteTokenRequest\x1a\x1a.token.DeleteTokenResponseb\x06proto3"

var (
	file_proto_token_service_proto_rawDescOnce sync.Once
	file_proto_token_service_proto_rawDescData []byte
)

func file_proto_token_service_proto_rawDescGZIP() []byte {
	file_proto_token_service_proto_rawDescOnce.Do(func() {
		file_proto_token_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_service_proto_rawDesc), len(file_proto_token_service_proto_rawDesc)))
	})
	return file_proto_token_service_proto_rawDescData
}

var file_proto_token_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_token_service_proto_goTypes = []any{
	(*CreateTokenRequest)(nil),  // 0: token.CreateTokenRequest
	(*CreateTokenResponse)(nil), // 1: token.CreateTokenResponse
	(*ReadTokenRequest)(nil),    // 2: token.ReadTokenRequest
	(*ReadTokenResponse)(nil),   // 3: token.ReadTokenResponse
	(*UpdateTokenRequest)(nil),  // 4: token.UpdateTokenRequest
	(*UpdateTokenResponse)(nil), // 5: token.UpdateTokenResponse
	(*DeleteTokenRequest)(nil),  // 6: token.DeleteTokenRequest
	(*DeleteTokenResponse)(nil), // 7: token.DeleteTokenResponse
}
var file_proto_token_service_proto_depIdxs = []int32{
	0, // 0: token.TokenService.CreateToken:input_type -> token.CreateTokenRequest
	2, // 1: token.TokenService.ReadToken:input_type -> token.ReadTokenRequest
	4, // 2: token.TokenService.UpdateToken:input_type -> token.UpdateTokenRequest
	6, // 3: token.TokenService.DeleteToken:input_type -> token.DeleteTokenRequest
	1, // 4: token.TokenService.CreateToken:output_type -> token.CreateTokenResponse
	3, // 5: token.TokenService.ReadToken:output_type -> token.ReadTokenResponse
	5, // 6: token.TokenService.UpdateToken:output_type -> token.UpdateTokenResponse
	7, // 7: token.TokenService.DeleteToken:output_type -> token.DeleteTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_token_service_proto_init() }
func file_proto_token_service_proto_init() {
	if File_proto_token_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_service_proto_rawDesc), len(file_proto_token_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_service_proto_goTypes,
		DependencyIndexes: file_proto_token_service_proto_depIdxs,
		MessageInfos:      file_proto_token_service_proto_msgTypes,
	}.Build()
	File_proto_token_service_proto = out.File
	file_proto_token_service_proto_goTypes = nil
	file_proto_token_service_proto_depIdxs = nil
}
