name: Run autotest on multiple OS and architectures

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go program
        working-directory: ./autotests
        run: go run .
